### ISSUE TITLE
SSO falied when login the application from consumer tenant

### ISSUE THREAD

**Issue by JocelynGu135** [SAP-samples/cloud-cap-samples-java#233]
Dear colleagues,

I have deployed the app to BTP CF provider subaccount, created consumer subaccount, and successfully subscribed to the application. However, when I try to access the application from the consumer subaccount, just can use the "Default User". My I missing some configuration here？

![image](https://github.com/SAP-samples/cloud-cap-samples-java/assets/132032144/66512d73-45f0-48f1-99b3-912aa884bbc0)

**Comment by beckermarc** [comment]
The sample just uses an embedded demo Fiori launchpad. The default user is expected, as this part of the application is simply not configured. If you would embed the application into the Fiori launchpad service these things should work correctly.

So this is not an issue, but actually the expected behaviour. SSO worked, if you are able to see this screen. You have automatically logged in with your email address, but it is just not reflected in that part of the UI. If you for example create an Order under `Manage Orders` you will see your User ID in the "Created By" area.
